#ifndef _JRC_CONSTANTS_H
#define _JRC_CONSTANTS_H

const char JRC_MSG_SHUTDOWN = '!'
const char JRC_MSG_NOIGNORE = '#'
const char JRC_MSG_IP = '$'
const char JRC_MSG_PWD = '%'
const char JRC_MSG_TIME = '&'
const char JRC_MSG_UNDO = '-'
const char JRC_MSG_NOEVENT = '?'
const char JRC_MSG_SERVERAUTH = '@'
const char JRC_MSG_NAME = 'A'
const char JRC_MSG_PASSWORD = 'B'
const char JRC_MSG_LEAVE = 'C'
const char JRC_MSG_JOIN = 'D'
const char JRC_MSG_MESSAGE = 'E'
const char JRC_MSG_PRIVATEMESSAGE = 'F'
const char JRC_MSG_NUMERICINFO = 'G'
const char JRC_MSG_GENERALINFO = 'H'
const char JRC_MSG_INFO = 'I'
const char JRC_MSG_IGNORE = 'J'
const char JRC_MSG_KICK = 'K'
const char JRC_MSG_BAN = 'L'
const char JRC_MSG_GAG = 'M'
const char JRC_MSG_KEEPOUT = 'N'
const char JRC_MSG_PERMROOM = 'P'
const char JRC_MSG_SETVALUE = 'R'
const char JRC_MSG_OP = 'S'
const char JRC_MSG_MAIL = 'T'
const char JRC_MSG_LOG = 'U'
const char JRC_MSG_WAITLIST = 'V'
const char JRC_MSG_SETINFO = 'W'
const char JRC_MSG_REFRESH = 'Z'
const char JRC_MSG_WHOIS = '^' // - also the "why"
const char JRC_MSG_USERINFO = 'a'
const char JRC_MSG_ROOMINFO = 'b'
const char JRC_MSG_ROOMUSERLIST = 'c'
const char JRC_MSG_SERVERINFO = 'g'
const char JRC_MSG_SPECIFICINFO = 'h'
const char JRC_MSG_SERVERMESSAGE = 'w'
const char JRC_MSG_REQUESTFAILED = 'x'
const char JRC_MSG_NOTFOUND = 'y'
const char JRC_MSG_ACCESSDENIED = 'z'
const char JRC_MSG_SERVERCHALLENGE = '~'

#endif
