#ifndef _JRC_CONSTANTS_H
#define _JRC_CONSTANTS_H

#define JRC_MSG_SHUTDOWN '!'
#define JRC_MSG_NOIGNORE '#'
#define JRC_MSG_IP '$'
#define JRC_MSG_PWD '%'
#define JRC_MSG_TIME '&'
#define JRC_MSG_UNDO '-'
#define JRC_MSG_NOEVENT '?'
#define JRC_MSG_SERVERAUTH '@'
#define JRC_MSG_NAME 'A'
#define JRC_MSG_PASSWORD 'B'
#define JRC_MSG_LEAVE 'C'
#define JRC_MSG_JOIN 'D'
#define JRC_MSG_MESSAGE 'E'
#define JRC_MSG_PRIVATEMESSAGE 'F'
#define JRC_MSG_NUMERICINFO 'G'
#define JRC_MSG_GENERALINFO 'H'
#define JRC_MSG_INFO 'I'
#define JRC_MSG_IGNORE 'J'
#define JRC_MSG_KICK 'K'
#define JRC_MSG_BAN 'L'
#define JRC_MSG_GAG 'M'
#define JRC_MSG_KEEPOUT 'N'
#define JRC_MSG_PERMROOM 'P'
#define JRC_MSG_SETVALUE 'R'
#define JRC_MSG_OP 'S'
#define JRC_MSG_MAIL 'T'
#define JRC_MSG_LOG 'U'
#define JRC_MSG_WAITLIST 'V'
#define JRC_MSG_SETINFO 'W'
#define JRC_MSG_REFRESH 'Z'
#define JRC_MSG_WHOIS '^' // - also the "why"
#define JRC_MSG_USERINFO 'a'
#define JRC_MSG_ROOMINFO 'b'
#define JRC_MSG_ROOMUSERLIST 'c'
#define JRC_MSG_SERVERINFO 'g'
#define JRC_MSG_SPECIFICINFO 'h'
#define JRC_MSG_SERVERMESSAGE 'w'
#define JRC_MSG_REQUESTFAILED 'x'
#define JRC_MSG_NOTFOUND 'y'
#define JRC_MSG_ACCESSDENIED 'z'
#define JRC_MSG_SERVERCHALLENGE '~'

#endif
